"""Add cached image columns to ExerciseCatalog

Revision ID: 127620721344
Revises: aeff27d16340
Create Date: 2025-12-01 17:39:57.217693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127620721344'
down_revision = 'aeff27d16340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_image_main', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('local_image_secondary', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_catalog', schema=None) as batch_op:
        batch_op.drop_column('local_image_secondary')
        batch_op.drop_column('local_image_main')

    # ### end Alembic commands ###
