"""Add cached image fields

Revision ID: 1a79e33c40bc
Revises: a45c228d5089
Create Date: 2025-11-20 18:09:39.712240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a79e33c40bc'
down_revision = 'a45c228d5089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_meal', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_member_meal_user_slot'))
        batch_op.create_foreign_key("fk_member_meal_user_id","user", ["user_id"],["id"])


    with op.batch_alter_table('member_meal_ingredient', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_member_meal_ingredient_meal_id'))
        batch_op.create_foreign_key(
              "fk_member_meal_ingredient_food_id",
              "food",
              ["food_id"],
              ["id"]
)
        batch_op.create_foreign_key(
              "fk_member_meal_ingredient_meal_id",
              "member_meal",
               ["meal_id"],
               ["id"]
)


    with op.batch_alter_table('trainer_meal', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_trainer_meal_member_slot'))
        batch_op.create_foreign_key(
              "fk_trainer_meal_member_id",
              "user",
              ["member_id"],
              ["id"]
)
        batch_op.create_foreign_key(
              "fk_trainer_meal_trainer_id",
              "user",
              ["trainer_id"],
              ["id"]
)


    with op.batch_alter_table('trainer_meal_ingredient', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_trainer_meal_ingredient_meal_id'))
        batch_op.create_foreign_key(
              "fk_trainer_meal_ingredient_meal_id",
              "trainer_meal",
              ["meal_id"],
              ["id"]
)
        batch_op.create_foreign_key(
              "fk_trainer_meal_ingredient_food_id",
              "food",
               ["food_id"],
              ["id"]
)


    # 1. Add columns (username nullable for now)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('theme_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('macro_target_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('macro_ratio_protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('macro_ratio_carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('macro_ratio_fats', sa.Float(), nullable=True))

    # 2. Run raw SQL AFTER batch completes
    conn = op.get_bind()
    conn.execute(sa.text("""
       UPDATE user
       SET username = COALESCE(
              SUBSTR(email, 1, INSTR(email, '@') - 1),
              'user_' || id
       )
       WHERE username IS NULL
       """))

       # 3. Enforce NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)

       # 4. Add unique constraint
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_username', ['username'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('macro_ratio_fats')
        batch_op.drop_column('macro_ratio_carbs')
        batch_op.drop_column('macro_ratio_protein')
        batch_op.drop_column('macro_target_mode')
        batch_op.drop_column('theme_mode')
        batch_op.drop_column('username')

    with op.batch_alter_table('trainer_meal_ingredient', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainer_meal', ['meal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_trainer_meal_ingredient_meal_id'), ['meal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trainer_meal', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['trainer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_trainer_meal_member_slot'), ['trainer_id', 'member_id', 'meal_slot'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('member_meal_ingredient', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member_meal', ['meal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_member_meal_ingredient_meal_id'), ['meal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('member_meal', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_member_meal_user_slot'), ['user_id', 'meal_slot'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
