"""Add username to User

Revision ID: a45c228d5089
Revises: 602724d59fea
Create Date: 2025-11-18 17:40:54.334204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45c228d5089'
down_revision = '602724d59fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_meal', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_member_meal_user_slot'))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('member_meal_ingredient', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_member_meal_ingredient_meal_id'))
        batch_op.create_foreign_key(None, 'member_meal', ['meal_id'], ['id'])
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])

    with op.batch_alter_table('trainer_meal', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_trainer_meal_member_slot'))
        batch_op.create_foreign_key(None, 'user', ['trainer_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['member_id'], ['id'])

    with op.batch_alter_table('trainer_meal_ingredient', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_trainer_meal_ingredient_meal_id'))
        batch_op.create_foreign_key(None, 'trainer_meal', ['meal_id'], ['id'])
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('theme_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('macro_target_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('macro_ratio_protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('macro_ratio_carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('macro_ratio_fats', sa.Float(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('macro_ratio_fats')
        batch_op.drop_column('macro_ratio_carbs')
        batch_op.drop_column('macro_ratio_protein')
        batch_op.drop_column('macro_target_mode')
        batch_op.drop_column('theme_mode')
        batch_op.drop_column('username')

    with op.batch_alter_table('trainer_meal_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainer_meal', ['meal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_trainer_meal_ingredient_meal_id'), ['meal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trainer_meal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['trainer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_trainer_meal_member_slot'), ['trainer_id', 'member_id', 'meal_slot'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('member_meal_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'member_meal', ['meal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_member_meal_ingredient_meal_id'), ['meal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('member_meal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_member_meal_user_slot'), ['user_id', 'meal_slot'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.drop_table('message')
    # ### end Alembic commands ###
